name: Mainline merge

on:
  push:
    branches:
      - main

env:
  run_number: ${GITHUB_RUN_NUMBER}

permissions:
  checks: write

jobs:
  build-and-package:
    name: Commit Stage API definition release candidate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out pr branch
        uses: actions/checkout@v3
      - name: View working folder
        run:  tree
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compile
        run: |
          ls -lash
          mvn clean compile
      - name: Unit test
        run: run_unittest.sh

      #TODO: Replace with GitHub packages
      # - name: "Zip API definition, Postman collection"
      #   run: |
      #     zip artifacts.zip api-definitions/skeleton-api.oas.yaml output/postman.collection.json
      
      # - name: "Setup artifact repository CLI (Jfrog CLI)"
      #   uses: jfrog/setup-jfrog-cli@v2
      #   env:
      #     JF_ENV_1: ${{ secrets.JF_SECRET }}
      # - name: "Upload to artifact repository (Jfrog Artifactory)"
      #   run: |
      #     jf rt ping
      #     jf rt upload artifacts.zip default-api-generic-local/com.acmeps/skeleton-api/artifacts.${{ env.run_number }}.zip
          