name: PR build workflow

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  checks: write

jobs:
  build-source-code:
    name: Build and test source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out pr branch
        uses: actions/checkout@v3
      - name: View working folder
        run:  tree
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test environments
        run: |
          mvn -version
          echo $JAVA_HOME
      - name: Compile
        run: |
          cd chapter8
          mvn --batch-mode clean compile
      - name: Unit test
        run: run_unittest.sh
      